#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: What are claims related to a specific food/food component’s health effect? 
#+ description: What are claims related to a specific food/food component’s health effect? 
#+ tags:
#+   - default
#+ method: GET
#+ pagination: 100
#+ defaults:
#+   - claimlabel: Calcium contributes to normal muscle function
# enumerate:
#   - food:
#     - https://foodb.ca/compounds/FDB003513

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?claim ?claim_label ?statement ?statement_label
WHERE {
    ?mp mp:argues  ?claim.
    ?claim rdfs:label ?claim_label .
    ?statement mp:supports ?claim .
    ?statement rdfs:label ?statement_label .
    FILTER(lang(?label) = ?__2letterLanguageTag) . # filter on a given language, like "es", "nl", "se"
    FILTER regex(?label, ?_claimlabel)
}
