#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: Retrieve all foods in the EFSA opinion for all claims
#+ description: List all foods mentioned the claims the EFSA opinions 
#+ tags:
#+   - Explore
#+ method: GET
#+ pagination: 100

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sc: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?claim_label ?food ?food_name ?food_type ?food_source ?unit ?value ?frequency 
WHERE {
    ?mp mp:argues  ?claim .
    ?claim rdfs:label ?claim_label .
    ?mp mp:represents ?hfe .
    ?hfe fhcp:hasPhenotype ?pheno .
    ?hfe fhcp:hasFood ?food .
    ?food rdfs:label ?food_name .
    ?food fhcp:source ?food_source .
    ?food rdf:type ?food_type .
	?food sc:recommendedIntake ?rec_intake . 
    ?rec_intake sc:doseUnit ?unit .
    ?rec_intake sc:doseValue ?value . 
    ?rec_intake sc:frequency ?frequency .
}




