#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: List the most frequently cited publications in the EFSA opinions.
#+ description: Which publication was most frequently cited in the EFSA opinions?
#+ tags:
#+   - Get claims metadata
#+ method: GET

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?reference ?reference_label (count(?claim ) as ?number_of_claims)
WHERE  {
    ?mp mp:argues  ?claim.
    ?claim rdfs:label ?claim_label .
    ?statement mp:supports ?claim .
    ?reference mp:supports ?statement .
    ?reference rdfs:label ?reference_label .
    ?reference rdf:type mp:Reference . 
}
GROUP BY ?reference ?reference_label