#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: List all health claims associated with a specific phenotype. 
#+ description: What are health claims associated with phenotypes/diseases?
#+ tags:
#+   - Retrieve claims
#+ method: GET
#+ defaults:
#+   - phenotypelabel: Normal energy-yielding metabolism

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?phenotype ?claim_label ?claim
{
    ?mp mp:argues ?claim.
    ?claim rdfs:label ?claim_label .
    ?mp mp:represents ?hfe .
    ?hfe fhcp:hasPhenotype ?phenotype .
    ?phenotype rdfs:label ?phenotype_label .
    ?hfe fhcp:hasFood ?food .
    FILTER regex(?phenotype_label, ?_phenotypelabel)
}
