#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary:  List all claims related to the health effect of a specific food
#+ description: What are claims related to a specific food/food component health effect? 
#+ tags:
#+   - Retrieve claims
#+ method: GET
#+ pagination: 100
#+ defaults:
#+   - foodlabel: calcium
# enumerate:
#   - food:
#     - https://foodb.ca/compounds/FDB003513

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  ?claim_label ?claim
WHERE {
    ?mp mp:argues  ?claim.
    ?claim rdfs:label ?claim_label .
    ?mp mp:represents ?hfe .
    ?hfe fhcp:hasPhenotype ?pheno .
    ?hfe fhcp:hasFood ?food .
    ?food rdfs:label ?food_label .
    FILTER regex(?food_label, ?_foodlabel,  "i")
    # FILTER (?food = ?_foodcomponent_iri)
}
