#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: Retrieve all health effects in the EFSA opinion for all claims
#+ description: List all health effects mentioned the claims the EFSA opinions 
#+ tags:
#+   - Explore
#+ method: GET
#+ pagination: 100

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sc: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?claim_label ?hfe_label ?effect_type ?pheno ?umls
WHERE {
    ?mp mp:argues  ?claim .
    ?claim rdfs:label ?claim_label .
    ?mp mp:represents ?hfe .
    ?hfe rdf:type ?hfe_type .
    ?hfe rdfs:label ?hfe_label .
    ?hfe_type rdfs:label ?effect_type .
    ?hfe fhcp:hasPhenotype ?pheno .
    ?pheno owl:sameAs ?umls .
}



