#+ endpoint: https://graphdb.dumontierlab.com/repositories/FoodHealthClaimsKG
#+ endpoint_in_url: False
#+ summary: List all supporting statements for a specific claim
#+ description: What are the supporting statements about a food health claim?
#+ tags:
#+   - Get claims metadata
#+ method: GET
#+ pagination: 100
#+ defaults:
#+   - claimlabel: Calcium contributes to normal muscle function
# enumerate:
#   - food:
#     - https://foodb.ca/compounds/FDB003513

PREFIX mp: <http://purl.org/mp/>
PREFIX fhcp: <http://www.w3id.org/foodhkg/props/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?claim ?statement ?statement_label
WHERE {
    ?mp mp:argues ?claim.
    ?claim rdfs:label ?_claimlabel .
    ?statement mp:supports ?claim .
    ?statement rdfs:label ?statement_label .
    # FILTER(lang(?claim_label) = ?__2letterLanguageTag) . # filter on a given language, like "es", "nl", "se"
    # FILTER regex(?claim_label, ?_claimlabel)
}
